### ISSUE TITLE
Add hotspot in pano View

### ISSUE THREAD

**Issue by vitrinh282** [szt243660543/360VR#1]
does app has support add hotspots ?

**Comment by szt243660543** [comment]
Yes, vr  sdk support add  hotspots, please refer to SZT_TouchDemo, which contains an instructions.

**Comment by vitrinh282** [comment]
![screen shot 2017-07-14 at 1 41 32 pm](https://user-images.githubusercontent.com/28979711/28201221-4a76afa8-689a-11e7-9cdf-63ee4cc4ea1b.png)
i can't build project sdk demo

**Comment by vitrinh282** [comment]
![screen shot 2017-07-14 at 1 50 51 pm](https://user-images.githubusercontent.com/28979711/28201496-7e671afe-689b-11e7-8492-fae9fec02fd9.png)
with VRExample project

**Comment by szt243660543** [comment]
run VRExample project, this project is not support the simulator,run on a real machine. (the simulator will make a mistake.)

**Comment by vitrinh282** [comment]
thanks, it works.

**Comment by vitrinh282** [comment]
one more thing

// 要使用热点拾取功能，一定需要设置该接口
    [self.sztLibrary setFocusPicking:YES];
     
    // 热点拾取方法   object为要被拾取的对象
    SZTTouch *touch = [[SZTTouch alloc] initWithTouchObject:object];
    
    // 拾取的三个状态
    [touch willTouchCallBack:^(GLKVector3 vec) {
        NSLog(@"will select");
    }];
    
    [touch didTouchCallback:^(GLKVector3 vec) {
        NSLog(@"select");
    }];
    
    [touch endTouchCallback:^(GLKVector3 vec) {
        NSLog(@"will leave");
    }];

this code above is callback after we add hotspots and touch in them ?

**Comment by szt243660543** [comment]
Yes, you need to set up [self.sztLibrary setFocusPicking:YES] ;  and then you can pick it up using the SZTTouch method.
